# Generated by Django 4.2.2 on 2023-06-25 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jointable',
            old_name='img_id',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='jointable',
            old_name='user_id',
            new_name='user',
        ),
    ]
