# Generated by Django 4.2.2 on 2023-06-26 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_rename_img_id_jointable_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='img_promt',
            new_name='img_prompt',
        ),
    ]
