# Generated by Django 4.2.2 on 2023-06-26 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=100)),
                ('toggle', models.BooleanField(default=False)),
                ('feature_desc', models.TextField()),
            ],
        ),
    ]
